### ISSUE TITLE
Font Color on Forms with Dark Background on Pages

### ISSUE THREAD

**Issue by aileenfree** [godaddy/wp-escapade-theme#63]
I am using the theme with a dark (almost black) background with light text,and any form I add to the site is unusable because the font in the forms is the same as the main font color. Most forms automatically use white background for the boxes and most are not changeable.

**Comment by EvanHerman** [comment]
Hi @aileenfree 

You can use CSS to tweak the text in those input fields. If you provide a link to your site with an example we can help provide CSS specific to you.

Evan

**Comment by EvanHerman** [comment]
Hi @aileenfree 

It looks like there are some styles in there that are setting the color on those input fields. You can try the following to force them to always be a darker color:

```css
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea,
.select2-container .select2-choice {
   color: #333333;
}
```

You can add that right into the 'Additional CSS' section in the customizer. You can get there from the dashboard by going to 'Appearance > Customize > Additional CSS' and just copying the above CSS into that field.

Let us know if that helps!

**Comment by aileenfree** [comment]
Thanks Evan,

That solved the problem of the display of what is in the fields, but while
typing into the form fields the font is still light. Do you know how to fix
that?

-Aileen

**Comment by EvanHerman** [comment]
@aileenfree Ah yes, sorry about that. You can just add a `:focus` psedo state for each of those in that list above (except for the select2-container). So In all the CSS would be:

```css
input[type="text"],
input[type="email"],
input[type="url"],
input[type="password"],
input[type="search"],
input[type="number"],
input[type="tel"],
input[type="range"],
input[type="date"],
input[type="month"],
input[type="week"],
input[type="time"],
input[type="datetime"],
input[type="datetime-local"],
input[type="color"],
textarea,
input[type="text"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="password"]:focus,
input[type="search"]:focus,
input[type="number"]:focus,
input[type="tel"]:focus,
input[type="range"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="week"]:focus,
input[type="time"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="color"]:focus,
textarea:focus,
.select2-container .select2-choice {
   color: #333333;
}
```

That _should_ also change things as you are typing into the fields.

Evan
